/*
 * ColorChooser.java
 *
 * Copyright 2008 Peter Vennemann
 * 
 * This file is part of JPIV.
 *
 * JPIV is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JPIV is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with JPIV.  If not, see <http://www.gnu.org/licenses/>. 
 */

package jpiv2;

import java.awt.Color;

import javax.swing.colorchooser.AbstractColorChooserPanel;

/**
 * A simplified color chooser dialog.
 * 
 */
public class ColorChooserDlg extends javax.swing.JDialog {

	/**
	 * Constructor.
	 * 
	 * @param parent
	 *            The parent frame.
	 * @param modal
	 *            Display as modal or not.
	 */
	public ColorChooserDlg(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.parent = parent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		jColorChooser = new javax.swing.JColorChooser();
		jPanel = new javax.swing.JPanel();
		jButtonOk = new javax.swing.JButton();
		jButtonCancel = new javax.swing.JButton();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});

		getContentPane().add(jColorChooser, java.awt.BorderLayout.CENTER);

		jButtonOk.setText("OK");
		jButtonOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonOkActionPerformed(evt);
			}
		});

		jPanel.add(jButtonOk);

		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		jPanel.add(jButtonCancel);

		getContentPane().add(jPanel, java.awt.BorderLayout.SOUTH);

	}// GEN-END:initComponents

	private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOkActionPerformed
		userOption = OK_OPTION;
		this.dispose();
	}// GEN-LAST:event_jButtonOkActionPerformed

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCancelActionPerformed
		userOption = CANCEL_OPTION;
		this.dispose();
	}// GEN-LAST:event_jButtonCancelActionPerformed

	/**
	 * Display the dialog. This method returns after the user has made a choice.
	 * 
	 * @param title
	 *            Title of the dialog.
	 * @param oldColor
	 *            This color is returned if the user presses 'cancel'.
	 * @return The choosen color.
	 */
	public Color showDialog(String title, Color oldColor) {
		// remove unneccessary panels
		AbstractColorChooserPanel[] panels = jColorChooser.getChooserPanels();
		jColorChooser.removeChooserPanel(panels[1]);
		jColorChooser.removeChooserPanel(panels[2]);
		jColorChooser.setPreviewPanel(new javax.swing.JPanel());
		// set title and resize window
		this.setTitle(title);
		this.pack();
		int width = this.getWidth();
		int height = this.getHeight();
		int xpos = parent.getWidth() / 2 - width;
		int ypos = parent.getHeight() / 2 - height;
		this.setBounds(xpos, ypos, width, height);
		// show() returns when the dialog is disposed (if modal).
		this.setVisible(true);
		// return the choosen color
		Color newColor = jColorChooser.getColor();
		if (userOption == OK_OPTION) {
			return newColor;
		} else {
			return oldColor;
		}
	}

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
		dispose();
	}// GEN-LAST:event_closeDialog

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonCancel;
	private javax.swing.JButton jButtonOk;
	private javax.swing.JColorChooser jColorChooser;
	private javax.swing.JPanel jPanel;
	// End of variables declaration//GEN-END:variables

	private java.awt.Frame parent;
	/** User pressed 'ok' */
	public final int OK_OPTION = 0;
	/** User pressed 'cancel' */
	public final int CANCEL_OPTION = 1;

	private int userOption;
}
